const fs = require('fs');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><html><body></body></html>`);
global.window = dom.window;
global.document = dom.window.document;
global.navigator = dom.window.navigator;
const script = fs.readFileSync('node_modules/3dmol/build/3Dmol.js', 'utf8');
dom.window.eval(script);
console.log(Object.keys(dom.window.$3Dmol));
