const $3Dmol = { Parsers: { mmtf: () => [] } };
global.$3Dmol = $3Dmol as any;
import { MolProcessor } from './src/lib/MolProcessor.ts';
import fs from 'fs';
const text = fs.readFileSync('1HVR.pdb', 'utf8');
const processor = new MolProcessor(text, 'pdb');
processor.calculateSecondaryStructure('pdb');
console.log("Helices length:", processor.ss_per_residue.filter(r => r.ss_type === 'helix').length);
console.log("Sheets length:", processor.ss_per_residue.filter(r => r.ss_type === 'sheet').length);
console.log("Loops length:", processor.ss_per_residue.filter(r => r.ss_type === 'loop').length);
console.log("Undetermined length:", processor.ss_per_residue.filter(r => r.ss_type === 'undetermined').length);
