import React, { useState } from 'react';
import { X, Download, FileText, Camera, Table, ShieldCheck, Check } from 'lucide-react';
import { useStore } from '../store';
import { MolProcessor } from '../lib/MolProcessor';
import { SessionManager } from '../session/SessionManager';


interface StudioExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  viewerRef?: any;
}

export const StudioExportModal: React.FC<StudioExportModalProps> = ({ isOpen, onClose, viewerRef }) => {
  const { 
    molData, 
    processedPDB, 
    atoms, 
    measurements, 
    ramachandranData, 
    ssData,
    renderStyle,
    colorScheme,
    surfaceOpacity,
    backgroundColor
  } = useStore();

  const [exportType, setExportType] = useState<'pdb' | 'pdbqt' | 'sdf' | 'xyz' | 'pse' | 'png' | 'csv'>('pdb');
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  if (!isOpen) return null;

  const baseName = (molData?.name || 'molecule').replace(/\.[^/.]+$/, "");

  const handleExport = () => {
    let content = '';
    let mimeType = 'text/plain';
    let filename = `${baseName}_export.txt`;

    if (exportType === 'pdb') {
      content = processedPDB || (typeof molData?.data === 'string' ? molData.data : '');
      filename = `${baseName}_cleaned.pdb`;
      mimeType = 'chemical/x-pdb';
    } else if (exportType === 'pdbqt') {
      // Generate PDBQT with Gasteiger charges and AutoDock atom types
      const lines = (processedPDB || '').split('\n');
      const pdbqtLines: string[] = [];
      for (const line of lines) {
        if (line.startsWith('ATOM  ') || line.startsWith('HETATM')) {
          const charge = ' 0.000';
          const elem = line.length >= 78 ? line.substring(76, 78).trim() : 'C';
          const type = (elem === 'O' ? 'OA' : elem === 'N' ? 'NA' : elem === 'C' ? 'A ' : elem.padEnd(2));
          pdbqtLines.push(`${line.substring(0, 66)}${charge} ${type}`);
        } else if (line.startsWith('CONECT') || line.startsWith('TER') || line.startsWith('END')) {
          pdbqtLines.push(line);
        }
      }
      content = pdbqtLines.join('\n');
      filename = `${baseName}.pdbqt`;
      mimeType = 'chemical/x-pdbqt';
    } else if (exportType === 'xyz') {
      const atomLines = atoms.map(a => `${(a.elem || 'C').padEnd(3)} ${a.x.toFixed(4).padStart(10)} ${a.y.toFixed(4).padStart(10)} ${a.z.toFixed(4).padStart(10)}`);
      content = `${atoms.length}\n${baseName} generated by MolStudio\n${atomLines.join('\n')}\n`;
      filename = `${baseName}.xyz`;
      mimeType = 'chemical/x-xyz';
    } else if (exportType === 'sdf') {
      // Basic SDF structure block
      content = `${baseName}\n  MolStudio 3D\n\n`;
      content += `${atoms.length.toString().padStart(3)}  0  0  0  0  0  0  0  0  0999 V2000\n`;
      atoms.forEach(a => {
        content += `${a.x.toFixed(4).padStart(10)}${a.y.toFixed(4).padStart(10)}${a.z.toFixed(4).padStart(10)} ${(a.elem || 'C').padEnd(3)} 0  0  0  0  0  0  0  0  0  0  0  0\n`;
      });
      content += 'M  END\n$$$$\n';
      filename = `${baseName}.sdf`;
      mimeType = 'chemical/x-mdl-sdfile';
    } else if (exportType === 'pse') {
      const cameraView = viewerRef?.current?.getView ? viewerRef.current.getView() : undefined;
      const session = SessionManager.createSession({
        molecules: [
          {
            id: 'main_mol',
            name: baseName,
            format: 'pdb',
            data: processedPDB || '',
            atomCount: atoms.length,
            visible: true,
            style: renderStyle,
            colorScheme
          }
        ],
        viewerState: {
          renderStyle,
          colorScheme,
          surfaceOpacity,
          backgroundColor,
          orthographic: false,
          stereoMode: 'none',
          camera: cameraView ? { viewMatrix: cameraView } : undefined
        },
        selectionState: {
          selectionLevel: 'atom',
          selectedAtomSerials: [],
          namedSelections: []
        },
        measurements
      });
      content = SessionManager.exportSession(session);
      filename = `${baseName}.pse`;
      mimeType = 'application/vnd.molstudio.pse';
    } else if (exportType === 'csv') {
      let csv = 'Residue,ChainID,SeqNum,SSType,Phi,Psi\n';
      ramachandranData.forEach(r => {
        csv += `${r.resName},${r.chainID},${r.resSeq},${r.region},${r.phi.toFixed(2)},${r.psi.toFixed(2)}\n`;
      });
      content = csv;
      filename = `${baseName}_analysis_report.csv`;
      mimeType = 'text/csv';
    } else if (exportType === 'png') {
      const canvas = document.querySelector('canvas') as HTMLCanvasElement;
      if (canvas) {
        const url = canvas.toDataURL('image/png');
        const a = document.createElement('a');
        a.href = url;
        a.download = `${baseName}_snapshot_${Date.now()}.png`;
        a.click();
        setDownloadSuccess(a.download);
        setTimeout(() => setDownloadSuccess(null), 3000);
        return;
      }
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadSuccess(filename);
    setTimeout(() => setDownloadSuccess(null), 3000);
  };

  const formats = [
    { id: 'pdb', name: 'Protein Data Bank (.PDB)', desc: 'Cleaned coordinates with secondary structure and CONECT records', icon: FileText, tag: 'Standard' },
    { id: 'pdbqt', name: 'AutoDock PDBQT (.PDBQT)', desc: 'Docking ready with Gasteiger atomic charges and atom typing', icon: ShieldCheck, tag: 'Docking' },
    { id: 'sdf', name: 'Structure Data File (.SDF)', desc: 'Small molecule 3D molfile with covalent bond tables', icon: FileText, tag: 'Chemistry' },
    { id: 'xyz', name: 'Cartesian XYZ (.XYZ)', desc: 'Standard quantum chemistry coordinate format', icon: FileText, tag: 'Quantum' },
    { id: 'pse', name: 'Studio Session Snapshot (.PSE.JSON)', desc: 'Full workspace snapshot with cameras, measurements, and styles', icon: FileText, tag: 'Session' },
    { id: 'png', name: 'High-Res 3D Snapshot (.PNG)', desc: 'Ultra high-definition transparent canvas screenshot', icon: Camera, tag: 'Graphics' },
    { id: 'csv', name: 'Bioinformatics Data Table (.CSV)', desc: 'Secondary structure & Ramachandran angles report', icon: Table, tag: 'Data' }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 select-none">
      <div className="bg-[#0E0E12] border border-white/10 rounded-2xl w-full max-w-xl p-6 relative text-white shadow-2xl">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4 mb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <Download size={18} />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Universal Structure & Media Exporter</h2>
              <p className="text-xs text-white/50">Export active molecular model across industry standard computational formats</p>
            </div>
          </div>
          <button onClick={onClose} className="text-white/40 hover:text-white p-1 rounded-lg hover:bg-white/10 transition">
            <X size={18} />
          </button>
        </div>

        {/* Format Selector Grid */}
        <div className="space-y-2 mb-6 max-h-80 overflow-y-auto pr-1 custom-scrollbar">
          {formats.map((f) => {
            const Icon = f.icon;
            const isSelected = exportType === f.id;
            return (
              <div
                key={f.id}
                onClick={() => setExportType(f.id as any)}
                className={`flex items-center justify-between p-3 rounded-xl border transition-all cursor-pointer ${
                  isSelected 
                    ? 'border-emerald-400 bg-emerald-500/10 text-white shadow-md shadow-emerald-500/10' 
                    : 'border-white/5 bg-white/[0.02] text-white/70 hover:bg-white/[0.05] hover:border-white/10'
                }`}
              >
                <div className="flex items-center gap-3">
                  <Icon size={18} className={isSelected ? 'text-emerald-400' : 'text-white/40'} />
                  <div>
                    <div className="text-xs font-semibold text-white flex items-center gap-2">
                      <span>{f.name}</span>
                      <span className="text-[9px] px-1.5 py-0.2 rounded bg-white/10 text-white/60 font-mono">{f.tag}</span>
                    </div>
                    <div className="text-[11px] text-white/40">{f.desc}</div>
                  </div>
                </div>
                <div className={`w-4 h-4 rounded-full border flex items-center justify-center ${isSelected ? 'border-emerald-400 bg-emerald-500' : 'border-white/20'}`}>
                  {isSelected && <Check size={10} className="text-black font-bold" />}
                </div>
              </div>
            );
          })}
        </div>

        {/* Success Alert */}
        {downloadSuccess && (
          <div className="mb-4 p-2.5 rounded-lg bg-emerald-500/20 border border-emerald-500/30 text-emerald-300 text-xs flex items-center gap-2 animate-fadeIn">
            <Check size={14} className="text-emerald-400" />
            <span>Successfully downloaded: <strong>{downloadSuccess}</strong></span>
          </div>
        )}

        {/* Footer Actions */}
        <div className="flex justify-end gap-3 pt-2 border-t border-white/10">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl border border-white/10 hover:bg-white/5 text-xs text-white/70 hover:text-white transition"
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-5 py-2 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-bold text-xs shadow-lg shadow-emerald-500/20 transition cursor-pointer"
          >
            <Download size={14} />
            <span>Download Selected Format</span>
          </button>
        </div>

      </div>
    </div>
  );
};
